# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreData' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
]

  target 'CoreDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoreDataUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
